### PR TITLE
Link to settings from Plugin's tab (from Hyphenator plugin).

### PR DESCRIPTION
**Pull request by odie2**
Link to settings from Plugin's tab in admin.

### CODE REVIEW

**Comment by ideag** [comment]
again, thanks for the idea, but I'll be implementing an object oriented version of this.

**Comment by ideag** [comment]
@odie2 any more PR's before I publish 0.8.0 ? :)

**Comment by odie2** [comment]
@ideag Yes, translation .pot fix and update, Polish translation and maybe some others. But I can do it tomorrow, today I am busy.

BTW: For what activating checkbox for widget? When I discovered plugin, I was confused as I would active widget before go to setitngs.

**Comment by ideag** [comment]
@odie2 the widget is optional. If it is not used, the widget code does not get loaded, thus minimizing the plugin footprint.

**Comment by odie2** [comment]
@ideag Maybe, I just see in my Widget's tab, most of plugins with optional widgets always have widgets activated, so asking as it may be confusing.

**Comment by ideag** [comment]
I know most of them do that, but I prefer to keep my plugins as light as possible, especially the `tiny*` family. I'll add info how to activate widget to the F.A.Q. section.

**Pull request closed without merging**
